--  
-- SQL script to Drop primary and foreign key constraints
--   
-- Generated to reverse add_fk_constraints.sql
-- Drop foreign keys first, then primary keys
--
--  

-- ********************************************************************************************
-- ********************************************************************************************
-- Drop foreign key table constraints (must be dropped before primary keys)
-- ********************************************************************************************
-- ********************************************************************************************

ALTER TABLE ADDRESS_ALIAS DROP CONSTRAINT IF EXISTS ADDRESS_ALIAS_FK1;
ALTER TABLE ADDRESS_ALIAS DROP CONSTRAINT IF EXISTS ADDRESS_ALIAS_FK2;
ALTER TABLE ADDRESS_ALIAS DROP CONSTRAINT IF EXISTS ADDRESS_ALIAS_FK3;

ALTER TABLE ADDRESS_DEFAULT_GEOCODE DROP CONSTRAINT IF EXISTS ADDRESS_DEFAULT_GEOCODE_FK1;
ALTER TABLE ADDRESS_DEFAULT_GEOCODE DROP CONSTRAINT IF EXISTS ADDRESS_DEFAULT_GEOCODE_FK2;

ALTER TABLE ADDRESS_DETAIL DROP CONSTRAINT IF EXISTS ADDRESS_DETAIL_FK1;
ALTER TABLE ADDRESS_DETAIL DROP CONSTRAINT IF EXISTS ADDRESS_DETAIL_FK2;
ALTER TABLE ADDRESS_DETAIL DROP CONSTRAINT IF EXISTS ADDRESS_DETAIL_FK3;
ALTER TABLE ADDRESS_DETAIL DROP CONSTRAINT IF EXISTS ADDRESS_DETAIL_FK4;
ALTER TABLE ADDRESS_DETAIL DROP CONSTRAINT IF EXISTS ADDRESS_DETAIL_FK5;
ALTER TABLE ADDRESS_DETAIL DROP CONSTRAINT IF EXISTS ADDRESS_DETAIL_FK6;

ALTER TABLE ADDRESS_FEATURE DROP CONSTRAINT IF EXISTS ADDRESS_FEATURE_FK1;
ALTER TABLE ADDRESS_FEATURE DROP CONSTRAINT IF EXISTS ADDRESS_FEATURE_FK2;

ALTER TABLE ADDRESS_MESH_BLOCK_2016 DROP CONSTRAINT IF EXISTS ADDRESS_MESH_BLOCK_2016_FK1;
ALTER TABLE ADDRESS_MESH_BLOCK_2016 DROP CONSTRAINT IF EXISTS ADDRESS_MESH_BLOCK_2016_FK2;
ALTER TABLE ADDRESS_MESH_BLOCK_2016 DROP CONSTRAINT IF EXISTS ADDRESS_MESH_BLOCK_2016_FK3;

ALTER TABLE ADDRESS_MESH_BLOCK_2021 DROP CONSTRAINT IF EXISTS ADDRESS_MESH_BLOCK_2021_FK1;
ALTER TABLE ADDRESS_MESH_BLOCK_2021 DROP CONSTRAINT IF EXISTS ADDRESS_MESH_BLOCK_2021_FK2;
ALTER TABLE ADDRESS_MESH_BLOCK_2021 DROP CONSTRAINT IF EXISTS ADDRESS_MESH_BLOCK_2021_FK3;

ALTER TABLE ADDRESS_SITE DROP CONSTRAINT IF EXISTS ADDRESS_SITE_FK1;

ALTER TABLE ADDRESS_SITE_GEOCODE DROP CONSTRAINT IF EXISTS ADDRESS_SITE_GEOCODE_FK1;
ALTER TABLE ADDRESS_SITE_GEOCODE DROP CONSTRAINT IF EXISTS ADDRESS_SITE_GEOCODE_FK2;
ALTER TABLE ADDRESS_SITE_GEOCODE DROP CONSTRAINT IF EXISTS ADDRESS_SITE_GEOCODE_FK3;

ALTER TABLE LOCALITY DROP CONSTRAINT IF EXISTS LOCALITY_FK1;
ALTER TABLE LOCALITY DROP CONSTRAINT IF EXISTS LOCALITY_FK2;
ALTER TABLE LOCALITY DROP CONSTRAINT IF EXISTS LOCALITY_FK3;

ALTER TABLE LOCALITY_ALIAS DROP CONSTRAINT IF EXISTS LOCALITY_ALIAS_FK1;
ALTER TABLE LOCALITY_ALIAS DROP CONSTRAINT IF EXISTS LOCALITY_ALIAS_FK2;

ALTER TABLE LOCALITY_NEIGHBOUR DROP CONSTRAINT IF EXISTS LOCALITY_NEIGHBOUR_FK1;
ALTER TABLE LOCALITY_NEIGHBOUR DROP CONSTRAINT IF EXISTS LOCALITY_NEIGHBOUR_FK2;

ALTER TABLE LOCALITY_POINT DROP CONSTRAINT IF EXISTS LOCALITY_POINT_FK1;

ALTER TABLE PRIMARY_SECONDARY DROP CONSTRAINT IF EXISTS PRIMARY_SECONDARY_FK1;
ALTER TABLE PRIMARY_SECONDARY DROP CONSTRAINT IF EXISTS PRIMARY_SECONDARY_FK2;
ALTER TABLE PRIMARY_SECONDARY DROP CONSTRAINT IF EXISTS PRIMARY_SECONDARY_FK3;

ALTER TABLE STREET_LOCALITY DROP CONSTRAINT IF EXISTS STREET_LOCALITY_FK1;
ALTER TABLE STREET_LOCALITY DROP CONSTRAINT IF EXISTS STREET_LOCALITY_FK2;
ALTER TABLE STREET_LOCALITY DROP CONSTRAINT IF EXISTS STREET_LOCALITY_FK3;
ALTER TABLE STREET_LOCALITY DROP CONSTRAINT IF EXISTS STREET_LOCALITY_FK4;
ALTER TABLE STREET_LOCALITY DROP CONSTRAINT IF EXISTS STREET_LOCALITY_FK5;

ALTER TABLE STREET_LOCALITY_ALIAS DROP CONSTRAINT IF EXISTS STREET_LOCALITY_ALIAS_FK1;
ALTER TABLE STREET_LOCALITY_ALIAS DROP CONSTRAINT IF EXISTS STREET_LOCALITY_ALIAS_FK2;
ALTER TABLE STREET_LOCALITY_ALIAS DROP CONSTRAINT IF EXISTS STREET_LOCALITY_ALIAS_FK3;
ALTER TABLE STREET_LOCALITY_ALIAS DROP CONSTRAINT IF EXISTS STREET_LOCALITY_ALIAS_FK4;

ALTER TABLE STREET_LOCALITY_POINT DROP CONSTRAINT IF EXISTS STREET_LOCALITY_POINT_FK1;

-- ********************************************************************************************
-- ********************************************************************************************
-- Drop primary key table constraints 
-- ********************************************************************************************
-- ********************************************************************************************

ALTER TABLE ADDRESS_ALIAS DROP CONSTRAINT IF EXISTS ADDRESS_ALIAS_PK;
ALTER TABLE ADDRESS_ALIAS_TYPE_AUT DROP CONSTRAINT IF EXISTS ADDRESS_ALIAS_TYPE_AUT_PK;
ALTER TABLE ADDRESS_CHANGE_TYPE_AUT DROP CONSTRAINT IF EXISTS ADDRESS_CHANGE_TYPE_AUT_PK;
ALTER TABLE ADDRESS_DEFAULT_GEOCODE DROP CONSTRAINT IF EXISTS ADDRESS_DEFAULT_GEOCODE_PK;
ALTER TABLE ADDRESS_DETAIL DROP CONSTRAINT IF EXISTS ADDRESS_DETAIL_PK;
ALTER TABLE ADDRESS_FEATURE DROP CONSTRAINT IF EXISTS ADDRESS_FEATURE_PK;
ALTER TABLE ADDRESS_MESH_BLOCK_2016 DROP CONSTRAINT IF EXISTS ADDRESS_MESH_BLOCK_2016_PK;
ALTER TABLE ADDRESS_MESH_BLOCK_2021 DROP CONSTRAINT IF EXISTS ADDRESS_MESH_BLOCK_2021_PK;
ALTER TABLE ADDRESS_SITE DROP CONSTRAINT IF EXISTS ADDRESS_SITE_PK;
ALTER TABLE ADDRESS_SITE_GEOCODE DROP CONSTRAINT IF EXISTS ADDRESS_SITE_GEOCODE_PK;
ALTER TABLE ADDRESS_TYPE_AUT DROP CONSTRAINT IF EXISTS ADDRESS_TYPE_AUT_PK;
ALTER TABLE FLAT_TYPE_AUT DROP CONSTRAINT IF EXISTS FLAT_TYPE_AUT_PK;
ALTER TABLE GEOCODED_LEVEL_TYPE_AUT DROP CONSTRAINT IF EXISTS GEOCODED_LEVEL_TYPE_AUT_PK;
ALTER TABLE GEOCODE_RELIABILITY_AUT DROP CONSTRAINT IF EXISTS GEOCODE_RELIABILITY_AUT_PK;
ALTER TABLE GEOCODE_TYPE_AUT DROP CONSTRAINT IF EXISTS GEOCODE_TYPE_AUT_PK;
ALTER TABLE LEVEL_TYPE_AUT DROP CONSTRAINT IF EXISTS LEVEL_TYPE_AUT_PK;
ALTER TABLE LOCALITY DROP CONSTRAINT IF EXISTS LOCALITY_PK;
ALTER TABLE LOCALITY_ALIAS DROP CONSTRAINT IF EXISTS LOCALITY_ALIAS_PK;
ALTER TABLE LOCALITY_ALIAS_TYPE_AUT DROP CONSTRAINT IF EXISTS LOCALITY_ALIAS_TYPE_AUT_PK;
ALTER TABLE LOCALITY_CLASS_AUT DROP CONSTRAINT IF EXISTS LOCALITY_CLASS_AUT_PK;
ALTER TABLE LOCALITY_NEIGHBOUR DROP CONSTRAINT IF EXISTS LOCALITY_NEIGHBOUR_PK;
ALTER TABLE LOCALITY_POINT DROP CONSTRAINT IF EXISTS LOCALITY_POINT_PK;
ALTER TABLE MB_2016 DROP CONSTRAINT IF EXISTS MB_2016_PK;
ALTER TABLE MB_2021 DROP CONSTRAINT IF EXISTS MB_2021_PK;
ALTER TABLE MB_MATCH_CODE_AUT DROP CONSTRAINT IF EXISTS MB_MATCH_CODE_AUT_PK;
ALTER TABLE PRIMARY_SECONDARY DROP CONSTRAINT IF EXISTS PRIMARY_SECONDARY_PK;
ALTER TABLE PS_JOIN_TYPE_AUT DROP CONSTRAINT IF EXISTS PS_JOIN_TYPE_AUT_PK;
ALTER TABLE STATE DROP CONSTRAINT IF EXISTS STATE_PK;
ALTER TABLE STREET_CLASS_AUT DROP CONSTRAINT IF EXISTS STREET_CLASS_AUT_PK;
ALTER TABLE STREET_LOCALITY DROP CONSTRAINT IF EXISTS STREET_LOCALITY_PK;
ALTER TABLE STREET_LOCALITY_ALIAS DROP CONSTRAINT IF EXISTS STREET_LOCALITY_ALIAS_PK;
ALTER TABLE STREET_LOCALITY_ALIAS_TYPE_AUT DROP CONSTRAINT IF EXISTS STREET_LOCALITY_ALIAS_TYPE__PK;
ALTER TABLE STREET_LOCALITY_POINT DROP CONSTRAINT IF EXISTS STREET_LOCALITY_POINT_PK;
ALTER TABLE STREET_SUFFIX_AUT DROP CONSTRAINT IF EXISTS STREET_SUFFIX_AUT_PK;
ALTER TABLE STREET_TYPE_AUT DROP CONSTRAINT IF EXISTS STREET_TYPE_AUT_PK;
